print('====== Desafio 03 =====')
print('Qual é a soma dos números A e B?')
a = input('Qual é o número A?  ')
b = input('Qual é o número B?  ')
soma = int(a) + int(b)
print('A soma de A + B é:', soma, '!')
